### ISSUE TITLE
Pluginloader throwing exception when loading non-lyokoplugin dll

### ISSUE THREAD

**Issue by TenDRILLL** [LyokoAPI/LyokoPluginLoader#1]
IFSCL startup screen breaks when a non-plugin dll is placed in the plugins folder. explicitly removing the file from the file list fixes the issue

**Comment by GoodOldJack12** [comment]
Final issue: 
LyokoAPI contains a Type 'LyokoAPIPlugin', therefore it is selected. However, obviously we need a subclass of LyokoAPIPlugin.

This has been fixed here:
https://github.com/LyokoAPI/LyokoPluginLoader/pull/2
